# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['associations',
     'astrometryFit',
     'astrometryModels',
     'ccdImage',
     'chi2',
     'frame',
     'gtransfo',
     'jointcalControl',
     'photometryFit',
     'photometryModels',
     'point',
     'projectionHandler',
    ],
    addUnderscore=False,
)
