# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(
    ['associations',
     'astrometryMappings',
     'astrometryModels',
     'ccdImage',
     'chi2',
     'fitter',
     'frame',
     'gtransfo',
     'jointcalControl',
     'photometryMappings',
     'photometryModels',
     'photometryTransfo',
     'projectionHandler',
     'star'
    ],
    addUnderscore=False,
)
