# -*- python -*-
from lsst.sconsUtils import scripts, targets, env
import os


flags = ["-fexceptions", "-DNSUPERNODAL", "-DNPARTITION"]

uname = os.uname()
if uname.sysname == 'Darwin' and uname.machine == 'arm64':
    flags.append('-faligned-allocation')

# fix failing cfht tests on Linux aarch64 with gcc
if uname.sysname == 'Linux' and uname.machine == 'aarch64':
    flags.append('-fno-expensive-optimizations')

for flag in flags:
    env["CFLAGS"].append(flag)
    env["CXXFLAGS"].append(flag)

scripts.BasicSConscript.lib()

