# -*- python -*-
from lsst.sconsUtils import scripts, targets, env

for flag in ("-fexceptions", "-DNSUPERNODAL", "-DNPARTITION"):
    env["CFLAGS"].append(flag)
    env["CXXFLAGS"].append(flag)

scripts.BasicSConscript.lib()

