from lsst.meas.extensions.astrometryNet import LoadAstrometryNetObjectsTask
config.photometryRefObjLoader.retarget(LoadAstrometryNetObjectsTask)
config.astrometryRefObjLoader.retarget(LoadAstrometryNetObjectsTask)
